//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriftModelYchebka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Id { get; set; }
        public Nullable<int> PilotId { get; set; }
        public string Model { get; set; }
        public string Engine { get; set; }
        public string Power { get; set; }
        public string WheelWidth { get; set; }
        public string ImageCar { get; set; }
    
        public virtual Pilot Pilots { get; set; }
    }
}
