//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriftModelYchebka
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DriftEntities : DbContext
    {
        public DriftEntities()
            : base("name=DriftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> cars { get; set; }
        public virtual DbSet<PairArrivals> pair_arrivals { get; set; }
        public virtual DbSet<Pilot> pilots { get; set; }
        public virtual DbSet<Qualification> qualifications { get; set; }
        public virtual DbSet<Stage> stages { get; set; }
        public virtual DbSet<Team> teams { get; set; }
        public virtual DbSet<Tournament> tournaments { get; set; }
        public virtual DbSet<Tracks> tracks { get; set; }
        public virtual DbSet<User> user { get; set; }
    }
}
