//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriftModelYchebka
{
    using System;
    using System.Collections.Generic;
    
    public partial class PairArrivals
    {
        public int Id { get; set; }
        public Nullable<int> StagesId { get; set; }
        public Nullable<int> Tour { get; set; }
        public Nullable<int> FirstPilotId { get; set; }
        public Nullable<int> SecondPilotId { get; set; }
        public Nullable<bool> FirstPilotWin { get; set; }
    
        public virtual Pilot FirstPilot { get; set; }
        public virtual Pilot SecondPilot { get; set; }
        public virtual Stage Stages { get; set; }
    }
}
