//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriftModelYchebka
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Qualification
    {
        public int Id { get; set; }
        public Nullable<int> StagesId { get; set; }
        public Nullable<int> PilotId { get; set; }
        public Nullable<int> PointFirstAttempt { get; set; }
        public Nullable<int> PointSecondAttempt { get; set; }

        [NotMapped]
        public int PointForQualification { get; set; }
        [NotMapped]
        public Nullable<int> BestAttempt
        {
            get => PointFirstAttempt > PointSecondAttempt ? PointFirstAttempt : PointSecondAttempt;
        }

        public virtual Pilot Pilots { get; set; }
        public virtual Stage Stages { get; set; }

        [NotMapped]
        public User User 
        {
            get
            {
                return App.User;
            }
        }  
    }
}
