//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriftModelYchebka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stage()
        {
            this.PairArrivals = new HashSet<PairArrivals>();
            this.Qualifications = new HashSet<Qualification>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TournamentId { get; set; }
        public Nullable<int> TrackId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PairArrivals> PairArrivals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Qualification> Qualifications { get; set; }
        public virtual Tournament Tournaments { get; set; }
        public virtual Tracks Tracks { get; set; }
    }
}
